local _, CLCDK = ...

CLCDK.DEBUG = false
CLCDK.VERSION = 9.02

CLCDK.PLAYER_NAME = UnitName("player")
CLCDK.PLAYER_RACE = select(2, UnitRace("player"))
CLCDK.PLAYER_CLASS = select(2, UnitClass("player"))

CLCDK.FONT = 'Interface\\AddOns\\CLC_DK\\Media\\iosevka-fixed-extendedheavy.ttf'

CLCDK.SPEC_BLOOD = 1
CLCDK.SPEC_FROST = 2
CLCDK.SPEC_UNHOLY = 3
CLCDK.SPEC_UNKNOWN = 5

CLCDK.DAY = 86400
CLCDK.HOUR = 3600 
CLCDK.MINUTE = 60

CLCDK.COLOR_WHITE = "|cffffffff"
CLCDK.COLOR_RED = "|cffff0000"
CLCDK.COLOR_GREEN = "|cff00ff00"

CLCDK.IS_BUFF = 2
CLCDK.IS_CD = 3
CLCDK.IS_ABILITY = 4

CLCDK.ITEM_LOAD_THRESHOLD = .5
CLCDK.UPDATE_INTERVAL = 0.1



CLCDK.CURRENT_SPEC = 5
CLCDK.MAX_RP = 100

CLCDK.GCD = 0
CLCDK.CURRENT_TIME = 0