local _, CLCDK = ...

CLCDK.DEBUG = false
CLCDK.VERSION = 11.05

CLCDK.PLAYER_RACE = select(2, UnitRace("player"))
CLCDK.PLAYER_CLASS = select(2, UnitClass("player"))

CLCDK.FONT = 'Interface\\AddOns\\CLCDK\\Media\\CascadiaMono-2404.23.ttf'
CLCDK.FONT_SIZE_L = 18
CLCDK.FONT_SIZE_M = 12
CLCDK.FONT_SIZE_S = 8

CLCDK.SPEC_BLOOD = 1
CLCDK.SPEC_FROST = 2
CLCDK.SPEC_UNHOLY = 3
CLCDK.SPEC_UNKNOWN = 5

CLCDK.COLOR_WHITE = "|cffffffff"
CLCDK.COLOR_RED = "|cffC41E3A" --DK Red
CLCDK.COLOR_GREEN = "|cff54BD47" --Old School Unholy Rune
CLCDK.COLOR_BLUE = "|cff2480A5" --Old School Frost Rune
CLCDK.COLOR_RUNES = "|cff808080" --Default Rune
CLCDK.COLOR_RUNIC_POWER = "|cFF00D1FF" --Default RP

CLCDK.IS_BUFF = 2
CLCDK.IS_CD = 3
CLCDK.IS_ABILITY = 4

CLCDK.UPDATE_INTERVAL = 0.066 -- Target 15fps
CLCDK.CD_DURATION_THRESHOLD = 10

CLCDK.GCD_SPELL_ID = 61304 --This is a dummy spell specifically for the GCD.


CLCDK.CURRENT_SPEC = 5
CLCDK.MAX_RP = 100

CLCDK.GCD = 0
CLCDK.CURRENT_TIME = 0
CLCDK.LOADED = false